[package]
name = "rassifier"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rassifier"
crate-type = ["cdylib"]

[dependencies]
csv = "1"
flate2 = "1"
lrtc = "0.1.4"
rayon = "1.7"
rustler = "0.36.1"
serde = { version = "1.0", features = ["derive"] }
zstd = "0.11"